apiVersion: apps/v1
kind: Deployment
metadata:
    name: sigueme-deployment
    labels:
        stage: production
        name: sigueme
        app: sigueme
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sigueme
    template:
        metadata:
            labels:
                stage: production
                app: sigueme
        spec:
            containers:
            -   name: sigueme
                image: registry.digitalocean.com/tyche-registry/sigueme:production
                imagePullPolicy: Always
                ports:
                -   containerPort: 3000
                env:
                -   name: DATABASE_URL
                    valueFrom:
                        secretKeyRef:
                            name: hades-secret
                            key: database_url
                -   name: NODE_ENV
                    valueFrom:
                        configMapKeyRef:
                            name: hades-configmap
                            key: node_env
                -   name: PORT
                    valueFrom:
                        configMapKeyRef:
                            name: hades-configmap
                            key: port
